// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cmxbiR2DDRv5pf3jozTs35
// Component: KkoYUQ8b6EO
import * as React from "react"
import { Link } from "gatsby"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import ActionButton from "../../ActionButton" // plasmic-import: pbv-Mbq112w/component
import Spacer from "../../Spacer" // plasmic-import: DkggFCItL8le/component
import Avatar from "../../Avatar" // plasmic-import: zQn5MXmA4Iq4/component
import Button from "../../Button" // plasmic-import: KS2sS7P07Kxk/component
import Tweet from "../../Tweet" // plasmic-import: DQbVzEvSWEa/component
import SideSection from "../../SideSection" // plasmic-import: SDjD8p4xQ4sE/component
import Trend from "../../Trend" // plasmic-import: YgSl-_C-qO67/component
import Suggestion from "../../Suggestion" // plasmic-import: JLZ56I7cGHEM/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen" // plasmic-import: t7HaUpRXzb9g/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_twitter.module.css" // plasmic-import: cmxbiR2DDRv5pf3jozTs35/projectcss
import * as sty from "./PlasmicFeed.module.css" // plasmic-import: KkoYUQ8b6EO/css
import MagicIcon from "./icons/PlasmicIcon__Magic" // plasmic-import: hRfI-xOlu_Md/icon
import TwitterIcon from "./icons/PlasmicIcon__Twitter" // plasmic-import: s1zxaLzbirtO/icon
import HomeActiveIcon from "./icons/PlasmicIcon__HomeActive" // plasmic-import: Acs0hDr57fIq/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2" // plasmic-import: z5m5-HMfNVfe/icon
import NotificationsIcon from "./icons/PlasmicIcon__Notifications" // plasmic-import: YHNSby5eqkfC/icon
import MessagesIcon from "./icons/PlasmicIcon__Messages" // plasmic-import: JezJIidJdJ8n/icon
import BookmarksIcon from "./icons/PlasmicIcon__Bookmarks" // plasmic-import: e1UmjQMky48q/icon
import ListsIcon from "./icons/PlasmicIcon__Lists" // plasmic-import: GOM0Mx3uQBaU/icon
import ProfileIcon from "./icons/PlasmicIcon__Profile" // plasmic-import: -05dwHONNw4l/icon
import MoreIcon from "./icons/PlasmicIcon__More" // plasmic-import: tAiJ0nHJvwC7/icon
import PictureIcon from "./icons/PlasmicIcon__Picture" // plasmic-import: qAE8JKp3Jh_1/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3" // plasmic-import: vOjLBN68ozA9/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4" // plasmic-import: L_wqqGHL9RKT/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5" // plasmic-import: MPzt9vOkLR_B/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7" // plasmic-import: H9_GtIxo8aeU/icon
import SearchIcon from "./icons/PlasmicIcon__Search" // plasmic-import: iEbVAAIu33FV/icon
import image22R4JEb5W3Yh7 from "./images/image2.png" // plasmic-import: 2R4JEb5w3Yh7/picture
import image5R7N5Iqu4MdKr from "./images/image5.png" // plasmic-import: R7N5IQU4MdKR/picture
import image4UAfdbKu8AOh3 from "./images/image4.png" // plasmic-import: UAfdbKU8AOh3/picture
import image76Pp0YcDx1MNy from "./images/image7.png" // plasmic-import: 6Pp0ycDX1mNY/picture
import image68QAkZtRvUfJx from "./images/image6.png" // plasmic-import: 8QAkZtRvUFJx/picture
import image8QorS0Vtaj0Ec from "./images/image8.png" // plasmic-import: QorS0VTAJ0ec/picture
import imageQdb88UaOl from "./images/image.png" // plasmic-import: qdb-8_8uaOL-/picture

export const PlasmicFeed__VariantProps = new Array()

export const PlasmicFeed__ArgProps = new Array()

function PlasmicFeed__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__cej2B
            )}
          >
            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__vnIkw
              )}
            >
              {(
                hasVariant(globalVariants, "screen", "desktop") ? false : true
              ) ? (
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__oDXhk
                  )}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__vBm1M
                    )}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rrJs9)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      src={{
                        src: image22R4JEb5W3Yh7,
                        fullWidth: 225,
                        fullHeight: 223,
                        aspectRatio: undefined,
                      }}
                    />
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__mg6Tn
                    )}
                  >
                    {"Home"}
                  </div>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__k9G0
                    )}
                    options={["medium", "primary"]}
                    slot={"25"}
                  >
                    <MagicIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg___84DKx
                      )}
                      role={"img"}
                    />
                  </ActionButton>
                </div>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "desktop") ? true : false
              ) ? (
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__pRqGz
                  )}
                >
                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__rBdcu
                    )}
                    options={["primary", "large"]}
                    slot={"25"}
                  >
                    <TwitterIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__g9Jk
                      )}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__tNg00
                    )}
                    options={["primary", "large"]}
                    slot={"25"}
                  >
                    <HomeActiveIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg___2Pqbi
                      )}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__vjgkS
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <Icon2Icon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg___56Mxi
                      )}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__zhMg8
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <NotificationsIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__s22JP
                      )}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__hWeQu
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <MessagesIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__e347N
                      )}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__qsKS
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <BookmarksIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__bl9Tv
                      )}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__jCUse
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <ListsIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__e8Snz
                      )}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__jfijs
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <ProfileIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__hYvpW
                      )}
                      role={"img"}
                    />
                  </ActionButton>

                  <ActionButton
                    className={classNames(
                      "__wab_instance",
                      sty.actionButton__xRwW8
                    )}
                    options={["large"]}
                    slot={"25"}
                  >
                    <MoreIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__nqJqX
                      )}
                      role={"img"}
                    />
                  </ActionButton>
                </div>
              ) : null}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__ogG8D
              )}
            >
              {(
                hasVariant(globalVariants, "screen", "desktop") ? true : false
              ) ? (
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__g5HDl
                  )}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox___8MTSm
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__ayJKq
                      )}
                    >
                      {"Home"}
                    </div>

                    <Spacer
                      className={classNames(
                        "__wab_instance",
                        sty.spacer__jSn4E
                      )}
                    />

                    <ActionButton
                      className={classNames(
                        "__wab_instance",
                        sty.actionButton___15PNi
                      )}
                      options={["medium", "primary"]}
                      slot={"25"}
                    >
                      <MagicIcon
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.svg__ml4Jo
                        )}
                        role={"img"}
                      />
                    </ActionButton>
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox___3I8FA
                    )}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.freeBox__l1QrK
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.freeBox__vew1N
                        )}
                      >
                        <Avatar
                          data-plasmic-name={"avatar"}
                          data-plasmic-override={overrides.avatar}
                          className={classNames("__wab_instance", sty.avatar)}
                        />
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.freeBox__jsq9
                      )}
                    >
                      <textarea
                        data-plasmic-name={"newTweetInput"}
                        data-plasmic-override={overrides.newTweetInput}
                        className={classNames(
                          defaultcss.textarea,
                          projectcss.textarea,
                          sty.newTweetInput
                        )}
                        placeholder={"What's happening?"}
                        rows={1}
                      />

                      <div
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.freeBox___4OQdV
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.freeBox__lXi8W
                          )}
                        >
                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton___7JCnm
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <PictureIcon
                              className={classNames(
                                defaultcss.all,
                                projectcss.all,
                                sty.svg__bdit7
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__vdLg1
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon3Icon
                              className={classNames(
                                defaultcss.all,
                                projectcss.all,
                                sty.svg__ibc6K
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__wRxqN
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon4Icon
                              className={classNames(
                                defaultcss.all,
                                projectcss.all,
                                sty.svg__ijJks
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__i0Zct
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon5Icon
                              className={classNames(
                                defaultcss.all,
                                projectcss.all,
                                sty.svg___8B6L0
                              )}
                              role={"img"}
                            />
                          </ActionButton>

                          <ActionButton
                            className={classNames(
                              "__wab_instance",
                              sty.actionButton__y0Ryz
                            )}
                            options={["medium", "primary"]}
                            slot={"25"}
                          >
                            <Icon7Icon
                              className={classNames(
                                defaultcss.all,
                                projectcss.all,
                                sty.svg__g0Dk5
                              )}
                              role={"img"}
                            />
                          </ActionButton>
                        </p.Stack>

                        <Spacer
                          className={classNames(
                            "__wab_instance",
                            sty.spacer__zw3F
                          )}
                        />

                        <Button
                          data-plasmic-name={"tweetButton"}
                          data-plasmic-override={overrides.tweetButton}
                          className={classNames(
                            "__wab_instance",
                            sty.tweetButton
                          )}
                          options={["primary"]}
                        >
                          {"Tweet"}
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              ) : null}

              <div
                data-plasmic-name={"tweetList"}
                data-plasmic-override={overrides.tweetList}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.tweetList
                )}
              >
                <Tweet
                  className={classNames("__wab_instance", sty.tweet__c0Dv)}
                />

                <Tweet
                  className={classNames("__wab_instance", sty.tweet___2RlHv)}
                  name={"Cassidy Williams"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___1FYA)}
                      displayHeight={"49px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"49px"}
                      src={{
                        src: image4UAfdbKu8AOh3,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  username={"@cassidoo"}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__vMpK6
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__a6Q74
                      )}
                    >
                      {"A new issue is coming your way, check your inbox!!"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.freeBox___9JfY3
                      )}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__sKrHv)}
                        displayHeight={"140px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"140px"}
                        src={{
                          src: image5R7N5Iqu4MdKr,
                          fullWidth: 240,
                          fullHeight: 240,
                          aspectRatio: undefined,
                        }}
                      />

                      <div
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.freeBox__huIjL
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            defaultcss.__wab_text,
                            sty.text__ax6Z1
                          )}
                        >
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                          >
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"rendezvous with cassidoo"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </span>
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            defaultcss.__wab_text,
                            sty.text___73CWh
                          )}
                        >
                          {"probably the best newsletter you'll ever read"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            defaultcss.__wab_text,
                            sty.text__tj61N
                          )}
                        >
                          {"cassidoo.co"}
                        </div>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__vTqne)}
                  name={"Max Stoiber"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___8DdE9)}
                      displayHeight={"49px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"49px"}
                      src={{
                        src: image76Pp0YcDx1MNy,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  username={"@mxstbr"}
                >
                  {
                    "Tell me you're a React developer without telling me you're a React developer."
                  }
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__sju9H)}
                />

                <Tweet
                  className={classNames("__wab_instance", sty.tweet___7LFsf)}
                  name={"Cassidy Williams"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ulra8)}
                      displayHeight={"49px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"49px"}
                      src={{
                        src: image4UAfdbKu8AOh3,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  username={"@cassidoo"}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__i1Cm0
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text___4C64
                      )}
                    >
                      {"A new issue is coming your way, check your inbox!!"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.freeBox__kx3Eu
                      )}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__lyNyu)}
                        displayHeight={"140px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"140px"}
                        src={{
                          src: image5R7N5Iqu4MdKr,
                          fullWidth: 240,
                          fullHeight: 240,
                          aspectRatio: undefined,
                        }}
                      />

                      <div
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.freeBox___3JuMl
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            defaultcss.__wab_text,
                            sty.text__k30QC
                          )}
                        >
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                          >
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"rendezvous with cassidoo"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </span>
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            defaultcss.__wab_text,
                            sty.text__b3Jq
                          )}
                        >
                          {"probably the best newsletter you'll ever read"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            defaultcss.__wab_text,
                            sty.text__nh0Fy
                          )}
                        >
                          {"cassidoo.co"}
                        </div>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </Tweet>

                <Tweet
                  className={classNames("__wab_instance", sty.tweet__azpRb)}
                  name={"Max Stoiber"}
                  photo={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__sHcJs)}
                      displayHeight={"49px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"49px"}
                      src={{
                        src: image76Pp0YcDx1MNy,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  username={"@mxstbr"}
                >
                  {
                    "Tell me you're a React developer without telling me you're a React developer."
                  }
                </Tweet>
              </div>
            </div>

            {(
              hasVariant(globalVariants, "screen", "desktop") ? true : false
            ) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__yisPq
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__tFdHs
                  )}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__ts4P
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.freeBox__jqhuP
                      )}
                    >
                      <SearchIcon
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.svg___1JZu
                        )}
                        role={"img"}
                      />
                    </div>

                    <input
                      data-plasmic-name={"searchInput"}
                      data-plasmic-override={overrides.searchInput}
                      className={classNames(
                        defaultcss.input,
                        projectcss.input,
                        sty.searchInput
                      )}
                      placeholder={"Search Twitter"}
                      size={1}
                      type={"text"}
                    />
                  </div>
                </div>

                <SideSection
                  className={classNames(
                    "__wab_instance",
                    sty.sideSection__mpx6A
                  )}
                  slot={
                    <React.Fragment>
                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend__pPw4G
                        )}
                        slot={"Entertainment"}
                      >
                        {
                          "Adele shares photo supporting Beyoncé's Black is King"
                        }
                      </Trend>

                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend___0EvDi
                        )}
                        slot={"COVID-19"}
                      >
                        {
                          "Thousands march in Berlin to protest COVID-19 restrictions"
                        }
                      </Trend>

                      <Trend
                        className={classNames(
                          "__wab_instance",
                          sty.trend__kMd6
                        )}
                        slot={"World nenws"}
                      >
                        {
                          "Russia banned from using its name, flag and anthem at the next two Olympic Games"
                        }
                      </Trend>
                    </React.Fragment>
                  }
                />

                <SideSection
                  className={classNames(
                    "__wab_instance",
                    sty.sideSection__ff1In
                  )}
                  slot={
                    <React.Fragment>
                      <Suggestion
                        className={classNames(
                          "__wab_instance",
                          sty.suggestion__lNeQc
                        )}
                        slot={"Mark Dalgleish      "}
                        slot2={"@markdalgleish"}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__uluAm)}
                          displayHeight={"49px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"49px"}
                          src={{
                            src: image68QAkZtRvUfJx,
                            fullWidth: 400,
                            fullHeight: 400,
                            aspectRatio: undefined,
                          }}
                        />
                      </Suggestion>

                      <Suggestion
                        className={classNames(
                          "__wab_instance",
                          sty.suggestion__ymQuo
                        )}
                        slot={"Guillermo Rauch  "}
                        slot2={"@rauchg"}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__wY54)}
                          displayHeight={"49px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"49px"}
                          src={{
                            src: image8QorS0Vtaj0Ec,
                            fullWidth: 400,
                            fullHeight: 400,
                            aspectRatio: undefined,
                          }}
                        />
                      </Suggestion>
                    </React.Fragment>
                  }
                >
                  {"Who to follow"}
                </SideSection>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__qcQbl
                  )}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__uKExK
                    )}
                  >
                    <p.PlasmicLink
                      className={classNames(
                        defaultcss.a,
                        projectcss.a,
                        defaultcss.__wab_text,
                        sty.link__gYwDs
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Terms"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        defaultcss.a,
                        projectcss.a,
                        defaultcss.__wab_text,
                        sty.link__qOkF
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Privacy policy"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        defaultcss.a,
                        projectcss.a,
                        defaultcss.__wab_text,
                        sty.link__n1P5N
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Cookies"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        defaultcss.a,
                        projectcss.a,
                        defaultcss.__wab_text,
                        sty.link__m48Wl
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Ads info"}
                    </p.PlasmicLink>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__rfePj
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__fZoi
                      )}
                    >
                      {"© 2021 Twitter, Inc."}
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            ) : null}
            {(
              hasVariant(globalVariants, "screen", "desktop") ? false : true
            ) ? (
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__drlq5
                )}
              >
                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__zkcX
                  )}
                  options={["medium", "primary"]}
                  slot={"25"}
                >
                  <HomeActiveIcon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg__v37Yj
                    )}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__a8PgP
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <SearchIcon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg__qhFr
                    )}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__lCsWg
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <NotificationsIcon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg__fCel2
                    )}
                    role={"img"}
                  />
                </ActionButton>

                <ActionButton
                  className={classNames(
                    "__wab_instance",
                    sty.actionButton__qP2Ur
                  )}
                  options={["medium"]}
                  slot={"25"}
                >
                  <MessagesIcon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg__hwv6N
                    )}
                    role={"img"}
                  />
                </ActionButton>
              </div>
            ) : null}
            {false ? (
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__xLyaz)}
                displayHeight={"731px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"411px"}
                src={{
                  src: imageQdb88UaOl,
                  fullWidth: 1079,
                  fullHeight: 1919,
                  aspectRatio: undefined,
                }}
              />
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "avatar",
    "newTweetInput",
    "tweetButton",
    "tweetList",
    "searchInput",
  ],

  avatar: ["avatar"],
  newTweetInput: ["newTweetInput"],
  tweetButton: ["tweetButton"],
  tweetList: ["tweetList"],
  searchInput: ["searchInput"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFeed__ArgProps,
      internalVariantPropNames: PlasmicFeed__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicFeed__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicFeed"
  } else {
    func.displayName = `PlasmicFeed.${nodeName}`
  }
  return func
}

export const PlasmicFeed = Object.assign(
  // Top-level PlasmicFeed renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    avatar: makeNodeComponent("avatar"),
    newTweetInput: makeNodeComponent("newTweetInput"),
    tweetButton: makeNodeComponent("tweetButton"),
    tweetList: makeNodeComponent("tweetList"),
    searchInput: makeNodeComponent("searchInput"),
    // Metadata about props expected for PlasmicFeed
    internalVariantProps: PlasmicFeed__VariantProps,
    internalArgProps: PlasmicFeed__ArgProps,
  }
)

export default PlasmicFeed
/* prettier-ignore-end */
